spring:
  boot:
    admin:
      client:
        url: http://sbadmin:9070
  cloud:
    consul:
      enabled: true
      host: consul
      discovery:
        preferIpAddress: false
        instance-id: ${spring.application.name}:${server.port}:${random.value}
